name: CI

on:
  push:
    branches: [ "release", "uat", "sit" ]
  pull_request:
    branches: [ "release", "uat", "sit" ]

jobs:
  build:
    name: Build .NET API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore NetCore.API.sln

      - name: Build
        run: dotnet build NetCore.API.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish NetCore.API.csproj --configuration Release --no-build --output ./publish

      - name: It worked
        run: echo "it worked"
